package com.mintpot.broadcasting.common.request;

import com.mintpot.broadcasting.common.enums.CategoryFile;
import lombok.Getter;
import lombok.Setter;
import org.springframework.web.multipart.MultipartFile;

import java.io.Serializable;

/**
 * TblContent generated by hbm2java
 */

@Getter
@Setter
public class ContentReq implements Serializable {
    private Long id;

    private String name;

    private CategoryFile type;

    private MultipartFile resource;
}
