package com.mintpot.broadcasting.common.request;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;


/**
 * TblDevice generated by hbm2java
 */

@Getter
public class DeviceReq implements Serializable {

  private @Setter Long id;

  private @Setter String name;

  private @Setter String imei;

  private @Setter String description;

  private Double latitude;

  private Double longitude;
}
