package com.mintpot.broadcasting.common.entities;

import com.mintpot.broadcasting.common.enums.CategoryFile;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.SQLDelete;
import org.hibernate.annotations.Where;

import javax.persistence.*;
import java.io.Serializable;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TblContent generated by hbm2java
 */

@Entity
@Getter
@Setter
@Table(name = "tbl_content")
@SQLDelete(sql = "update tbl_content ct set ct.active = 0 where ct.id = ?")
@Where(clause = "active = 1")
public class Content extends BaseEntity<Long> implements Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    private String name;

    @Enumerated(EnumType.STRING)
    private CategoryFile type;

    private String uri;

    private long size;

    @ManyToOne
    @JoinColumn(name = "org_id")
    private Organization organization;

    private boolean active;
}
